import { User, Service, Transaction, NotificationMsg, BankAccount, Beneficiary, NearbyItem, NearbyNews } from './types';


export const currentUser: User = {
  name: 'Alex Morgan',
  phone: '+95 9 791 234 567',
  nrc: '12/DAGANA(N)098212',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  tier: 'Diamond',
  points: 45200,
  balance: 12450750, // 12,450,750 MMK
  qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=MMK_WALLET_ALEX_MORGAN',
};

export const bankAccountsData: BankAccount[] = [
  {
    id: 'bank-1',
    bankName: 'Shwe Bank',
    bankCode: 'SHWE',
    accountName: 'Alex Morgan',
    accountNumber: '2001 8812 0092 1082',
    balance: 8500000,
    isLinked: true,
    logoColor: 'bg-amber-500 text-slate-900',
    isDefault: true,
  }
];

export const servicesData: Service[] = [
  // Top 7 featured on Home + More
  { id: '1', name: 'Bill Pay', category: 'bills', icon: 'FileText', color: 'bg-blue-50 text-blue-600', isFavourite: true, description: 'Pay electricity, water, internet' },
  { id: '2', name: 'Mobile Load', category: 'topup', icon: 'Smartphone', color: 'bg-emerald-50 text-emerald-600', isFavourite: true, description: 'Top up MPT, ATOM, Ooredoo, Mytel' },
  { id: '3', name: 'Utility', category: 'bills', icon: 'Zap', color: 'bg-amber-50 text-amber-600', isFavourite: true, description: 'YESC, ESE, YCDC payments' },
  { id: '4', name: 'EWA', category: 'finance', icon: 'Briefcase', color: 'bg-purple-50 text-purple-600', isFavourite: true, description: 'Earned Wage Access advance salary' },
  { id: '5', name: 'Gift Card', category: 'lifestyle', icon: 'Gift', color: 'bg-pink-50 text-pink-600', isFavourite: true, description: 'Steam, Google Play, Apple, MLBB' },
  { id: '6', name: 'Cash Collection', category: 'finance', icon: 'Banknote', color: 'bg-teal-50 text-teal-600', isFavourite: true, description: 'Doorstep cash collection service' },
  { id: '7', name: 'Bank Transfer', category: 'transfer', icon: 'Building2', color: 'bg-indigo-50 text-indigo-600', isFavourite: true, description: 'Instant transfer to 20+ Myanmar banks' },
  { id: '8', name: 'More', category: 'lifestyle', icon: 'Grid', color: 'bg-gray-100 text-gray-700', isFavourite: true, description: 'See all wallet features & services' },

  // Additional services in Catalog
  { id: '9', name: 'Non-Wallet Remittance', category: 'transfer', icon: 'Send', color: 'bg-amber-50 text-amber-600', isFavourite: false, description: 'Send cash to NRC/Phone without app' },
  { id: '10', name: 'Agent Cash In', category: 'finance', icon: 'ArrowDownToLine', color: 'bg-emerald-50 text-emerald-600', isFavourite: false, description: 'Top up cash via nearby agent' },
  { id: '11', name: 'Agent Cash Out', category: 'finance', icon: 'ArrowUpFromLine', color: 'bg-orange-50 text-orange-600', isFavourite: false, description: 'Withdraw cash at any authorized agent' },
  { id: '12', name: 'Internet & Fiber', category: 'bills', icon: 'Wifi', color: 'bg-cyan-50 text-cyan-600', isFavourite: false, description: 'FiberX, Mahar Net, Myanmar Net' },
  { id: '13', name: 'Insurance', category: 'finance', icon: 'ShieldCheck', color: 'bg-indigo-50 text-indigo-600', isFavourite: false, description: 'Health, travel & life cover' },
  { id: '14', name: 'Bus & Air Tickets', category: 'lifestyle', icon: 'Ticket', color: 'bg-rose-50 text-rose-600', isFavourite: false, description: 'Book express bus & domestic flights' },
  { id: '15', name: 'Game Top Up', category: 'topup', icon: 'Gamepad2', color: 'bg-violet-50 text-violet-600', isFavourite: false, description: 'Mobile Legends, PUBG, FreeFire' },
  { id: '16', name: 'Charity & Donation', category: 'lifestyle', icon: 'Heart', color: 'bg-red-50 text-red-600', isFavourite: false, description: 'Donate to verified foundations' },
];

export const historyData: Transaction[] = [
  { 
    id: 'tx1', 
    type: 'Merchant Pay', 
    subType: 'QR Payment',
    amount: -45000, 
    date: '2026-08-02 14:45', 
    status: 'completed', 
    merchant: 'Starbucks Junction City',
    referenceNo: 'MMK-8821901',
    fee: 0
  },
  { 
    id: 'tx2', 
    type: 'Wallet Transfer', 
    subType: 'P2P',
    amount: 150000, 
    date: '2026-08-02 10:30', 
    status: 'completed', 
    recipient: 'Sarah Jenkins (0978219921)',
    referenceNo: 'MMK-7712091',
    fee: 0
  },
  { 
    id: 'tx3', 
    type: 'Bill Pay', 
    subType: 'YESC Electricity',
    amount: -120500, 
    date: '2026-08-01 18:15', 
    status: 'completed', 
    merchant: 'YESC Yangon Electricity',
    accountNo: 'YESC-9921-01',
    referenceNo: 'MMK-6612981',
    fee: 0
  },
  { 
    id: 'tx4', 
    type: 'Linked Bank Top Up', 
    subType: 'KBZ Bank',
    amount: 500000, 
    date: '2026-08-01 09:00', 
    status: 'completed',
    accountNo: 'KBZ **** 4892',
    referenceNo: 'MMK-5512098',
    fee: 0
  },
  { 
    id: 'tx5', 
    type: 'Mobile Load', 
    subType: 'ATOM Myanmar',
    amount: -10000, 
    date: '2026-07-30 16:20', 
    status: 'completed',
    recipient: '09791234567',
    referenceNo: 'MMK-4412099',
    fee: 0
  },
  { 
    id: 'tx6', 
    type: 'Cash Out', 
    subType: 'Agent Withdrawal',
    amount: -200000, 
    date: '2026-07-28 11:10', 
    status: 'completed',
    merchant: 'San Chaung Authorized Agent #04',
    referenceNo: 'MMK-3310921',
    fee: 500
  },
];

export const notificationsData: NotificationMsg[] = [
  { id: 'n1', title: 'Payment Successful', message: 'You paid 45,000 MMK at Starbucks Junction City.', time: '10m ago', read: false, type: 'transaction' },
  { id: 'n2', title: 'Diamond Tier Perk!', message: 'Enjoy zero transfer fees across all KBZ and AYA linked accounts this month.', time: '2h ago', read: false, type: 'offer' },
  { id: 'n3', title: 'Cash In Confirmed', message: '500,000 MMK topped up from KBZ Bank ****4892.', time: '1d ago', read: true, type: 'transaction' },
  { id: 'n4', title: 'Loyalty Bonus Points', message: '+250 bonus points credited to your Diamond Wallet account.', time: '2d ago', read: true, type: 'system' },
];

export const initialBeneficiariesData: Beneficiary[] = [
  {
    id: 'b1',
    name: 'Aung Kyaw',
    phone: '09782119922',
    category: 'wallet',
    isFavorite: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'b2',
    name: 'Su Su Hlaing',
    phone: '09254009112',
    bankName: 'KBZ Bank',
    accountNo: '0981 1002 9981',
    category: 'bank',
    isFavorite: true,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'b3',
    name: 'Thura Soe',
    phone: '09971238811',
    bankName: 'AYA Bank',
    accountNo: '2001 8821 0092',
    category: 'bank',
    isFavorite: false,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'b4',
    name: 'May Zun',
    phone: '09420011998',
    nrc: '12/DAGANA(N)102911',
    category: 'non_wallet',
    isFavorite: false,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
  },
];

export const nearbyItemsData: NearbyItem[] = [
  // Merchants
  {
    id: 'm1',
    name: 'City Mart Supermarket (Junction City)',
    type: 'merchant',
    subCategory: 'Supermarket & Grocery',
    rating: 4.9,
    reviewsCount: 342,
    distanceKm: 0.4,
    area: 'Kamayut Township',
    address: 'Level 1, Junction City Shopping Center, Bogyoke Aung San Rd',
    phone: '+95 9 4500 1122',
    openHours: '09:00 AM - 09:30 PM',
    isOpenNow: true,
    isSuper: true,
    isPromo: true,
    isNew: false,
    services: ['QR Payment', 'Loyalty Cashback', 'E-Gift Voucher'],
    discountBadge: '10% Cashback',
    lat: 16.7812,
    lng: 96.1558,
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=MERCHANT_CITY_MART_JC',
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'm2',
    name: 'Starbucks Coffee (Sule Square)',
    type: 'merchant',
    subCategory: 'Café & Bakery',
    rating: 4.8,
    reviewsCount: 218,
    distanceKm: 0.8,
    area: 'Kyauktada Township',
    address: 'Ground Floor, Sule Square Tower, Sule Pagoda Road',
    phone: '+95 9 7800 2211',
    openHours: '07:30 AM - 08:30 PM',
    isOpenNow: true,
    isSuper: false,
    isPromo: true,
    isNew: false,
    services: ['QR Payment', 'Free Upgrade Coupon'],
    discountBadge: 'Free Size Upgrade',
    lat: 16.7765,
    lng: 96.1592,
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=MERCHANT_STARBUCKS_SULE',
    image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'm3',
    name: 'Ocean Supercenter (Hledan)',
    type: 'merchant',
    subCategory: 'Department Store',
    rating: 4.7,
    reviewsCount: 189,
    distanceKm: 1.2,
    area: 'Kamayut Township',
    address: 'Corner of Pyay Road and Hledan Road, Kamayut',
    phone: '+95 9 2500 3344',
    openHours: '08:30 AM - 09:00 PM',
    isOpenNow: true,
    isSuper: true,
    isPromo: false,
    isNew: true,
    services: ['QR Payment', 'Bill Payments', 'Card Top-Up'],
    lat: 16.8251,
    lng: 96.1324,
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=MERCHANT_OCEAN_HLEDAN',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'm4',
    name: 'Grab Kitchen & Hub (Bahan)',
    type: 'merchant',
    subCategory: 'Food Delivery & Dining',
    rating: 4.6,
    reviewsCount: 145,
    distanceKm: 1.5,
    area: 'Bahan Township',
    address: 'No. 45, Kabar Aye Pagoda Road, Bahan',
    phone: '+95 9 9600 8877',
    openHours: '10:00 AM - 10:00 PM',
    isOpenNow: true,
    isSuper: false,
    isPromo: true,
    isNew: false,
    services: ['QR Payment', 'Online Food Ordering'],
    discountBadge: '2,000 MMK Off',
    lat: 16.8090,
    lng: 96.1510,
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=MERCHANT_GRAB_BAHAN',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'm5',
    name: 'Capital Hypermarket (Yankin)',
    type: 'merchant',
    subCategory: 'Hypermarket',
    rating: 4.85,
    reviewsCount: 290,
    distanceKm: 2.1,
    area: 'Yankin Township',
    address: 'No. 14, Yankin Road, Yankin Township',
    phone: '+95 9 3100 5566',
    openHours: '08:00 AM - 09:00 PM',
    isOpenNow: true,
    isSuper: true,
    isPromo: true,
    isNew: false,
    services: ['QR Payment', 'Voucher Redemption'],
    discountBadge: 'Instant Voucher',
    lat: 16.8320,
    lng: 96.1610,
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=MERCHANT_CAPITAL_YANKIN',
    image: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=500&auto=format&fit=crop&q=80'
  },

  // Agents
  {
    id: 'a1',
    name: 'Sanchaung Diamond Authorized Agent #01',
    type: 'agent',
    subCategory: 'Super Authorized Agent',
    rating: 4.95,
    reviewsCount: 512,
    distanceKm: 0.2,
    area: 'Kamayut Township',
    address: 'No. 12, Sanchaung Street, Sanchaung (Near Hledan Center)',
    phone: '+95 9 7900 1100',
    openHours: '07:00 AM - 10:00 PM',
    isOpenNow: true,
    isSuper: true,
    isPromo: true,
    isNew: false,
    services: ['Cash In', 'Cash Out', 'NRC Remittance', 'Bill Payment', 'Bank Deposit'],
    cashLimitMMK: 10000000,
    discountBadge: '0% Cash Out Fee',
    lat: 16.8150,
    lng: 96.1310,
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=AGENT_SANCHAUNG_01',
    image: 'https://images.unsplash.com/photo-1556742049-0a670f4a4591?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'a2',
    name: 'Kyauktada Express Cash Agent #05',
    type: 'agent',
    subCategory: 'Bank Authorized Agent',
    rating: 4.9,
    reviewsCount: 403,
    distanceKm: 0.5,
    area: 'Kyauktada Township',
    address: 'No. 88, 38th Street (Middle Block), Kyauktada Township',
    phone: '+95 9 2600 4455',
    openHours: '08:00 AM - 08:00 PM',
    isOpenNow: true,
    isSuper: true,
    isPromo: false,
    isNew: false,
    services: ['Cash In', 'Cash Out', 'Bank Transfer', 'Non-Wallet Remittance'],
    cashLimitMMK: 8000000,
    lat: 16.7720,
    lng: 96.1620,
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=AGENT_KYAUKTADA_05',
    image: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'a3',
    name: 'Kamayut Mobile & Wallet Agent Hub',
    type: 'agent',
    subCategory: 'Mobile & Cash Hub',
    rating: 4.7,
    reviewsCount: 168,
    distanceKm: 0.8,
    area: 'Kamayut Township',
    address: 'Hledan Main Road, Corner of 2nd Street, Kamayut',
    phone: '+95 9 4210 9988',
    openHours: '08:30 AM - 09:00 PM',
    isOpenNow: true,
    isSuper: false,
    isPromo: false,
    isNew: true,
    services: ['Cash In', 'Cash Out', 'SIM Top-Up'],
    cashLimitMMK: 5000000,
    lat: 16.8210,
    lng: 96.1340,
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=AGENT_KAMAYUT_HUB',
    image: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'a4',
    name: 'Bahan VIP Wallet & Cash Agent',
    type: 'agent',
    subCategory: 'Super Authorized Agent',
    rating: 4.85,
    reviewsCount: 310,
    distanceKm: 1.1,
    area: 'Bahan Township',
    address: 'No. 102, Shwe Gon Daine Road, Bahan Township',
    phone: '+95 9 7700 3322',
    openHours: '08:00 AM - 09:30 PM',
    isOpenNow: true,
    isSuper: true,
    isPromo: true,
    isNew: false,
    services: ['Cash In', 'Cash Out', 'Doorstep Delivery', 'Foreign Currency Exch'],
    cashLimitMMK: 12000000,
    discountBadge: 'Free Refreshment',
    lat: 16.8040,
    lng: 96.1580,
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=AGENT_BAHAN_VIP',
    image: 'https://images.unsplash.com/photo-1556742111-a301076d9d18?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'a5',
    name: 'Yankin Center Authorized Agent',
    type: 'agent',
    subCategory: 'Convenience Agent',
    rating: 4.6,
    reviewsCount: 122,
    distanceKm: 1.8,
    area: 'Yankin Township',
    address: 'Near Yankin Center, Sayarsan Road, Yankin',
    phone: '+95 9 9800 6611',
    openHours: '08:00 AM - 08:30 PM',
    isOpenNow: true,
    isSuper: false,
    isPromo: false,
    isNew: false,
    services: ['Cash In', 'Cash Out', 'Utility Collection'],
    cashLimitMMK: 4000000,
    lat: 16.8290,
    lng: 96.1650,
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=AGENT_YANKIN_CENTER',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=500&auto=format&fit=crop&q=80'
  }
];

export const nearbyNewsData: NearbyNews[] = [
  {
    id: 'news1',
    title: 'Cash-In Bonus Festival at All Super Agents!',
    summary: 'Get 1,000 MMK instant wallet cashback bonus on any cash-in over 50,000 MMK at Super Authorized Agents.',
    date: 'Aug 2, 2026',
    category: 'Agent Update',
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=400&auto=format&fit=crop&q=80'
  },
  {
    id: 'news2',
    title: 'City Mart 10% QR Cashback Weekend',
    summary: 'Scan MoMoney QR at any City Mart or Ocean Supercenter this weekend to earn 10% instant points back.',
    date: 'Aug 1, 2026',
    category: 'Merchant Deal',
    imageUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=400&auto=format&fit=crop&q=80',
    merchantName: 'City Mart'
  },
  {
    id: 'news3',
    title: 'New Authorized Agent Hub Opened in Kamayut',
    summary: 'Serving 7 days a week with a guaranteed 20M MMK liquidity pool and zero queue times.',
    date: 'Jul 30, 2026',
    category: 'Agent Update',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0a670f4a4591?w=400&auto=format&fit=crop&q=80'
  },
  {
    id: 'news4',
    title: 'Grab Food 2,000 MMK Instant Voucher',
    summary: 'Pay with MoMoney Wallet on Grab Food and enjoy 2,000 MMK off orders over 10,000 MMK.',
    date: 'Jul 28, 2026',
    category: 'Promotion',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&auto=format&fit=crop&q=80',
    merchantName: 'Grab Food'
  }
];


